export const professions = {
  doctor: { _id: "67rdca3eeb7f6fgeed471818", name: "Доктор" },
  waiter: { _id: "67rdca3eeb7f6fgeed471820", name: "Официант" },
  physics: { _id: "67rdca3eeb7f6fgeed471814", name: "Физик" },
  engineer: { _id: "67rdca3eeb7f6fgeed471822", name: "Инженер" },
  actor: { _id: "67rdca3eeb7f6fgeed471824", name: "Актер" },
  cook: { _id: "67rdca3eeb7f6fgeed471829", name: "Повар" },
};
export const qualities = {
  tedious: {
    _id: "67rdca3eeb7f6fgeed471198",
    name: "Нудила",
    color: "primary",
  },
  strange: {
    _id: "67rdca3eeb7f6fgeed471100",
    name: "Странный",
    color: "secondary",
  },
  buller: { _id: "67rdca3eeb7f6fgeed4711012", name: "Троль", color: "success" },
  alcoholic: {
    _id: "67rdca3eeb7f6fgeed471101",
    name: "Алкоголик",
    color: "danger",
  },
  handsome: {
    _id: "67rdca3eeb7f6fgeed471102",
    name: "Красавчик",
    color: "info",
  },
  uncertain: {
    _id: "67rdca3eeb7f6fgeed471103",
    name: "Неуверенный",
    color: "dark",
  },
};

const users = [
  {
    _id: "67rdca3eeb7f6fgeed471815",
    name: "Джон Дориан",
    profession: professions.doctor,
    qualities: [qualities.tedious, qualities.uncertain, qualities.strange],
    completedMeetings: 36,
    rate: 2.5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed471821",
    name: "Говард Воловиц",
    profession: professions.engineer,
    qualities: [qualities.strange, qualities.tedious],
    completedMeetings: 72,
    rate: 3.5,
    bookmark: true,
  },

  {
    _id: "67rdca3eeb7f6fgeed471817",
    name: "Боб Келсо",
    profession: professions.doctor,
    qualities: [qualities.buller],
    completedMeetings: 100,
    rate: 3.5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed471818",
    name: "Рэйчел Грин",
    profession: professions.waiter,
    qualities: [qualities.uncertain],
    completedMeetings: 148,
    rate: 3.5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed471820",
    name: "Леонард Хофстедтер",
    profession: professions.physics,
    qualities: [qualities.strange, qualities.uncertain],
    completedMeetings: 126,
    rate: 3.5,
    bookmark: true,
  },

  {
    _id: "67rdca3eeb7f6fgeed471822",
    name: "Никола Тесла",
    profession: professions.engineer,
    qualities: [qualities.handsome],
    completedMeetings: 67,
    rate: 5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed471816",
    name: "Перри Кокс",
    profession: professions.doctor,
    qualities: [qualities.buller, qualities.handsome, qualities.alcoholic],
    completedMeetings: 15,
    rate: 2.5,
    bookmark: true,
  },
  {
    _id: "67rca3eeb7f6fd4fffро81f",
    name: "Джоуи Триббиани",
    profession: professions.actor,
    qualities: [qualities.uncertain, qualities.strange],
    completedMeetings: 99,
    rate: 3.5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed471823",
    name: "Моника Геллер",
    profession: professions.cook,
    qualities: [qualities.strange, qualities.uncertain],
    completedMeetings: 15,
    rate: 4.5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed471824",
    name: "Рататуй",
    profession: professions.cook,
    qualities: [qualities.handsome, qualities.buller],
    completedMeetings: 17,
    rate: 4.5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed4fff7181f",
    name: "Джоуи Триббиани",
    profession: professions.actor,
    qualities: [qualities.uncertain, qualities.strange],
    completedMeetings: 99,
    rate: 3.5,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181r",
    name: "Брэд Питт",
    profession: professions.actor,
    qualities: [qualities.handsome],
    completedMeetings: 200,
    rate: 5,
    bookmark: true,
  },

  {
    _id: "67rdeef6fgeed471817",
    name: "Боб Келсо",
    profession: professions.doctor,
    qualities: [qualities.buller],
    completedMeetings: 10,
    rate: 3.3,
    bookmark: true,
  },
  {
    _id: "67rca3eeb7f6fg",
    name: "Джон Дориан",
    profession: professions.doctor,
    qualities: [qualities.tedious, qualities.uncertain, qualities.strange],
    completedMeetings: 75,
    rate: 4,
    bookmark: true,
  },
  {
    _id: "67ca3eeb7fed4816",
    name: "Перри Кокс",
    profession: professions.doctor,
    qualities: [qualities.buller, qualities.handsome, qualities.alcoholic],
    completedMeetings: 13,
    rate: 2.9,
    bookmark: true,
  },

  {
    _id: "67rdeed47818",
    name: "Рэйчел Грин",
    profession: professions.waiter,
    qualities: [qualities.uncertain],
    completedMeetings: 122,
    rate: 3.6,
    bookmark: true,
  },
  {
    _id: "6rdca3ee7f6fgeed4719",
    name: "Шелдон Купер",
    profession: professions.physics,
    qualities: [qualities.strange, qualities.tedious],
    completedMeetings: 23,
    rate: 4.2,
    bookmark: true,
  },
  {
    _id: "67rda3e7f6fed471820",
    name: "Леонард Хофстедтер",
    profession: professions.physics,
    qualities: [qualities.strange, qualities.uncertain],
    completedMeetings: 105,
    rate: 3.3,
    bookmark: true,
  },
  {
    _id: "67ca3eeb7f6eed478",
    name: "Говард Воловиц",
    profession: professions.engineer,
    qualities: [qualities.strange, qualities.tedious],
    completedMeetings: 73,
    rate: 3.8,
    bookmark: true,
  },
  {
    _id: "rdeeb7f6fghed471822",
    name: "Никола Тесла",
    profession: professions.engineer,
    qualities: [qualities.handsome],
    completedMeetings: 69,
    rate: 4.8,
    bookmark: true,
  },
  {
    _id: "67rdca3eb7f6fgee471823",
    name: "Моника Геллер",
    profession: professions.cook,
    qualities: [qualities.strange, qualities.uncertain],
    completedMeetings: 13,
    rate: 4.3,
    bookmark: true,
  },
  {
    _id: "67ca3eeb7ffd6fgeed471824",
    name: "Рататуй",
    profession: professions.cook,
    qualities: [qualities.handsome, qualities.buller],
    completedMeetings: 18,
    rate: 4.7,
    bookmark: true,
  },
  {
    _id: "67rdca3eeb7f6fgeed47181f",
    name: "Джоуи Триббиани",
    profession: professions.actor,
    qualities: [qualities.uncertain, qualities.strange],
    completedMeetings: 89,
    rate: 3.7,
    bookmark: true,
  },
  {
    _id: "67rdcaeesdb7f6fgee47181r",
    name: "Брэд Питт",
    profession: professions.actor,
    qualities: [qualities.handsome],
    completedMeetings: 190,
    rate: 4.9,
    bookmark: true,
  },
];
function getUsers() {
  return users;
}

export default getUsers;
